version: '3.8'

services:
  node_app:
    build:
      context: ./my-first-app
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./my-first-app/.env
    ports:
      - "3000:3000"
    volumes:
      - ./my-first-app/.env:/app/.env
      - /root/logs:/app/logs
  log_app:
    build:
      context: ./logs-preview-server
      dockerfile: Dockerfile
    container_name: logs_preview
    ports:
      - "7000:7000"
    volumes:
      - /root/logs:/app/logs
